
 let json = {
  status: 200,
  url: 'https://api.github.com/repos/noahweasley/TimeLY/releases/latest',
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    'cache-control': 'private, max-age=60, s-maxage=60',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 28 Oct 2021 03:28:27 GMT',
    etag: 'W/"2a6c4c48aa483f6d5dc9fe91e759105d0d6a02fa7b84ae65109874b9aa46a22c"',
    'last-modified': 'Wed, 27 Oct 2021 23:11:28 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': 'repo',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': 'F2D9:3760:48AAD0:BA3D52:617A18DB',
    'x-oauth-scopes': 'admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, delete:packages, gist, notifications, repo, user, workflow, write:discussion, write:packages',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4986',
    'x-ratelimit-reset': '1635393500',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '14',
    'x-xss-protection': '0'
  },
  data: {
    url: 'https://api.github.com/repos/noahweasley/TimeLY/releases/52186220',
    assets_url: 'https://api.github.com/repos/noahweasley/TimeLY/releases/52186220/assets',
    upload_url: 'https://uploads.github.com/repos/noahweasley/TimeLY/releases/52186220/assets{?name,label}',
    html_url: 'https://github.com/noahweasley/TimeLY/releases/tag/v1.1.0',
    id: 52186220,
    author: {
      login: 'noahweasley',
      id: 43308031,
      node_id: 'MDQ6VXNlcjQzMzA4MDMx',
      avatar_url: 'https://avatars.githubusercontent.com/u/43308031?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/noahweasley',
      html_url: 'https://github.com/noahweasley',
      followers_url: 'https://api.github.com/users/noahweasley/followers',
      following_url: 'https://api.github.com/users/noahweasley/following{/other_user}',
      gists_url: 'https://api.github.com/users/noahweasley/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/noahweasley/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/noahweasley/subscriptions',
      organizations_url: 'https://api.github.com/users/noahweasley/orgs',
      repos_url: 'https://api.github.com/users/noahweasley/repos',
      events_url: 'https://api.github.com/users/noahweasley/events{/privacy}',
      received_events_url: 'https://api.github.com/users/noahweasley/received_events',
      type: 'User',
      site_admin: false
    },
    node_id: 'RE_kwDOFFiaFs4DHExs',
    tag_name: 'v1.1.0',
    target_commitish: 'master',
    name: 'v1.1.0',
    draft: false,
    prerelease: false,
    created_at: '2021-10-27T22:18:04Z',
    published_at: '2021-10-27T23:11:28Z',
    assets: [
      [Object]
    ],
    tarball_url: 'https://api.github.com/repos/noahweasley/TimeLY/tarball/v1.1.0',
    zipball_url: 'https://api.github.com/repos/noahweasley/TimeLY/zipball/v1.1.0',
    body: 'Implemented Todo list, fixed bugs and improved UI/UX'
  }
}